repos:
  - repo: local
    hooks:
      # -------------
      # Manual checks
      # -------------
      - id: pixi-pyproject-check
        name: pixi run pyproject-check
        entry: pixi run pyproject-check
        language: system
        pass_filenames: false
        stages: [manual]

      - id: license-headers-check
        name: pixi run license-check
        entry: pixi run license-check
        language: system
        pass_filenames: false
        stages: [manual]

      - id: pixi-py-lint-check
        name: pixi run py-lint-check
        entry: pixi run py-lint-check
        language: system
        pass_filenames: false
        stages: [manual]

      - id: pixi-py-format-check
        name: pixi run py-format-check
        entry: pixi run py-format-check
        language: system
        pass_filenames: false
        stages: [manual]

      - id: pixi-docstring-lint-check
        name: pixi run docstring-lint-check
        entry: pixi run docstring-lint-check
        language: system
        pass_filenames: false
        stages: [manual]

      - id: pixi-docstring-format-check
        name: pixi run docstring-format-check
        entry: pixi run docstring-format-check
        language: system
        pass_filenames: false
        stages: [manual]

      - id: pixi-nonpy-format-check
        name: pixi run nonpy-format-check
        entry: pixi run nonpy-format-check
        language: system
        pass_filenames: false
        stages: [manual]

      - id: pixi-notebook-lint-check
        name: pixi run notebook-lint-check
        entry: pixi run notebook-lint-check
        language: system
        pass_filenames: false
        stages: [manual]

      - id: pixi-unit-tests
        name: pixi run unit-tests
        entry: pixi run unit-tests
        language: system
        pass_filenames: false
        stages: [manual]
