# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        # Make project coverage informational (won't block PR)
        informational: true
    patch:
      default:
        # Require patch coverage but with threshold
        threshold: 1%
